-- Schema only, adapted from the four user_management MySQL dumps.
-- No accounts, uploaded files, or OTP records are imported.
CREATE TABLE users (
    user_id uuid PRIMARY KEY,
    "fullName" varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    password varchar(255) NOT NULL
);
-- Preserve case-insensitive email matching without requiring an extension.
CREATE UNIQUE INDEX users_email_unique ON users (lower(email));

CREATE TABLE mfa_otps (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(user_id),
    email varchar(255) NOT NULL,
    otp varchar(255) NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamptz NOT NULL
);
CREATE INDEX mfa_otps_user_id_idx ON mfa_otps(user_id);
CREATE INDEX mfa_otps_email_created_idx ON mfa_otps(lower(email), created_at DESC);

CREATE TABLE password_resets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL,
    otp varchar(255),
    expires_at timestamptz NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX password_resets_email_created_idx ON password_resets(lower(email), created_at DESC);

CREATE TABLE user_files (
    file_id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(user_id),
    file_name varchar(255),
    file_data bytea,
    masked_data bytea,
    iv bytea CHECK (iv IS NULL OR octet_length(iv) <= 16),
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    digital_signature varchar(255),
    random_number varchar(255)
);
CREATE INDEX user_files_user_created_idx ON user_files(user_id, created_at);
